### PR TITLE
Remove skeleton for variantsToVCF

### PR DESCRIPTION
**Pull request by siddharthab**
As per feedback from bioc review process.

### CODE REVIEW

**Comment by pgrosu** [comment]
That makes sense.  Is there a place where the meeting notes are placed?

Thanks,
~p

**Comment by siddharthab** [comment]
They are in the Bioc issue tracker. I think it is only visible to the submitter and the reviewers.

**Comment by deflaux** [comment]
Looks good Sid!

**Comment by pgrosu** [comment]
But Travis is sooo sad Nicole/Sid :(  Check it out here:

https://travis-ci.org/googlegenomics/api-client-r/builds/55698032

~p

**Comment by siddharthab** [comment]
Same reason here. Pull request merged before Travis could boot up. I checked Travis on my fork before merging this pull request so I knew the merge was safe. You can check that the main repo is Travis green after the merge.

**Comment by pgrosu** [comment]
Man, we're walking a tight rope on these.  Yup they look good.

Thanks,
~p

**Pull request merged**
