### PR TITLE
With feedback from jimhester's lintr.

### PR DESCRIPTION
**Pull request by siddharthab**
See comments dated today on https://github.com/googlegenomics/api-client-r/issues/18 for more context.

### CODE REVIEW

**Comment by deflaux** [comment]
Nice cleanup.

**Comment by pgrosu** [comment]
Looking forward to it - thanks Sid!

**Comment by pgrosu** [comment]
Sid, you might want to check Travis on this one too - it's complaining.  Here's the link:

https://travis-ci.org/googlegenomics/api-client-r/builds/55690830

~p

**Comment by siddharthab** [comment]
Umm.. that's because I merged it before Travis could boot up, so the pull request no longer existed when Travis looked for it.

**Pull request merged**
