### PR TITLE
Bioc submission prep -- stage 2

### PR DESCRIPTION
**Pull request by siddharthab**
Remaining changes for to be fully compliant for Bioc guidelines.

### CODE REVIEW

**Comment by deflaux** [comment]
Looks good Sid!  This should be good to go once Travis CI is happy.

Question for you: 
* Can we hang onto the rendered vignettes somewhere in the package until they are available on BioC like http://www.bioconductor.org/packages/release/bioc/vignettes/ggbio/inst/doc/ggbio.pdf
* I don't know how long it will take to actually get this into BioC and in the interim I'd like to keep that documentation around somewhere.  
* Perhaps we can [configure them to be removed from the installed package](http://stackoverflow.com/questions/13463103/inst-and-extdata-folders-in-r-packaging) like so:
`To exclude files from being installed, one can specify a list of exclude patterns in file .Rinstignore in the top-level source directory.`

**Comment by pgrosu** [comment]
I also like the additions Sid, but when I try this specific pull I get the following error.  Should the version restriction be changed?

```
> devtools::install_github("googlegenomics/api-client-r#31")
Downloading github repo siddharthab/api-client-r@master
Installing GoogleGenomics
Installing dependencies for GoogleGenomics:
S4Vectors
'/home/pgrosu/apps/R-3.1.0/bin/R' --vanilla CMD INSTALL  \
  '/tmp/RtmpMcwgsi/devtools934082fea6f/siddharthab-api-client-r-768cf0a'  \
  --library='/home/pgrosu/apps/R-3.1.0/library' --install-tests

ERROR: dependency âS4Vectorsâ is not available for package âGoogleGenomicsâ
* removing â/home/pgrosu/apps/R-3.1.0/library/GoogleGenomicsâ
Error: Command failed (1)
In addition: Warning message:
package âS4Vectorsâ is not available (for R version 3.1.0)
>
```
Thanks,
~p

**Comment by seandavi** [comment]
I hope you don't mind my chiming in.  You need to install Bioconductor
dependencies directly.  devtools::install_github does not automatically
pick up Bioconductor packages.  In particular, something like:

source('http://bioconductor.org/biocLite.R')
biocLite('GenomicAlignments')

will probably get you pretty close.

Sean

**Comment by siddharthab** [comment]
Another way:
source("http://bioconductor.org/biocLite.R") biocLite()
options(repos=biocinstallRepos())

Complete instructions in repo Readme. Thanks for trying this out. :)

**Comment by pgrosu** [comment]
Sid I actually did those steps previously.

Thanks Sean, I'll try that - it used to work before.

**Comment by siddharthab** [comment]
Maybe you are not using Bioc 3.0. This is something I will bring up with the bioc teams during review if we should be directly importing the S4Vector package. For now, this will not work with Bioc <3.0.

**Comment by pgrosu** [comment]
Below are all the exploratory analysis steps.  Maybe the R version should be restricted to a higher version.

```
> source("http://bioconductor.org/biocLite.R")
Bioconductor version 2.14 (BiocInstaller 1.14.3), ?biocLite for help
A newer version of Bioconductor is available for this version of R,
  ?BiocUpgrade for help
>
>
> biocLite()
BioC_mirror: http://bioconductor.org
Using Bioconductor version 2.14 (BiocInstaller 1.14.3), R version
  3.1.0.
>
>
> options(repos=biocinstallRepos())
>
>
> install.packages("devtools")
trying URL 'http://cran.fhcrc.org/src/contrib/devtools_1.7.0.tar.gz'
Content type 'application/x-gzip' length 130760 bytes (127 Kb)
opened URL
==================================================
downloaded 127 Kb

* installing *source* package âdevtoolsâ ...
** package âdevtoolsâ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/home/pgrosu/apps/R-3.1.0/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c devtools.c -o devtools.o
gcc -std=gnu99 -shared -L/usr/local/lib64 -o devtools.so devtools.o
installing to /home/pgrosu/apps/R-3.1.0/library/devtools/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (devtools)

The downloaded source packages are in
        â/tmp/RtmpopOLB9/downloaded_packagesâ
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
>
>
> devtools::install_github("googlegenomics/api-client-r#31")
Downloading github repo siddharthab/api-client-r@master
Installing GoogleGenomics
Installing dependencies for GoogleGenomics:
S4Vectors
'/home/pgrosu/apps/R-3.1.0/bin/R' --vanilla CMD INSTALL  \
  '/tmp/RtmpopOLB9/devtoolsb16b6428ab10/siddharthab-api-client-r-768cf0a'  \
  --library='/home/pgrosu/apps/R-3.1.0/library' --install-tests

ERROR: dependency âS4Vectorsâ is not available for package âGoogleGenomicsâ
* removing â/home/pgrosu/apps/R-3.1.0/library/GoogleGenomicsâ
Error: Command failed (1)
In addition: Warning message:
package âS4Vectorsâ is not available (for R version 3.1.0)
>
>
> biocLite('GenomicAlignments')
BioC_mirror: http://bioconductor.org
Using Bioconductor version 2.14 (BiocInstaller 1.14.3), R version
  3.1.0.
Installing package(s) 'GenomicAlignments'
trying URL 'http://bioconductor.org/packages/2.14/bioc/src/contrib/GenomicAlignments_1.0.6.tar.gz'
Content type 'application/x-gzip' length 1936108 bytes (1.8 Mb)
opened URL
==================================================
downloaded 1.8 Mb

* installing *source* package âGenomicAlignmentsâ ...
** libs
gcc -std=gnu99 -I/home/pgrosu/apps/R-3.1.0/include -DNDEBUG  -I/usr/local/include -I"/home/pgrosu/apps/R-3.1.0/library/IRanges/include"   -fpic  -g -O2  -c IRanges_stubs.c -o IRanges_stubs.o
gcc -std=gnu99 -I/home/pgrosu/apps/R-3.1.0/include -DNDEBUG  -I/usr/local/include -I"/home/pgrosu/apps/R-3.1.0/library/IRanges/include"   -fpic  -g -O2  -c R_init_GenomicAlignments.c -o R_init_GenomicAlignments.o
gcc -std=gnu99 -I/home/pgrosu/apps/R-3.1.0/include -DNDEBUG  -I/usr/local/include -I"/home/pgrosu/apps/R-3.1.0/library/IRanges/include"   -fpic  -g -O2  -c cigar_utils.c -o cigar_utils.o
gcc -std=gnu99 -I/home/pgrosu/apps/R-3.1.0/include -DNDEBUG  -I/usr/local/include -I"/home/pgrosu/apps/R-3.1.0/library/IRanges/include"   -fpic  -g -O2  -c encodeOverlaps_methods.c -o encodeOverlaps_methods.o
gcc -std=gnu99 -shared -L/usr/local/lib64 -o GenomicAlignments.so IRanges_stubs.o R_init_GenomicAlignments.o cigar_utils.o encodeOverlaps_methods.o
installing to /home/pgrosu/apps/R-3.1.0/library/GenomicAlignments/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (GenomicAlignments)

The downloaded source packages are in
        â/tmp/RtmpopOLB9/downloaded_packagesâ
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
>
>
> devtools::install_github("googlegenomics/api-client-r#31")
Downloading github repo siddharthab/api-client-r@master
Installing GoogleGenomics
Installing dependencies for GoogleGenomics:
S4Vectors
'/home/pgrosu/apps/R-3.1.0/bin/R' --vanilla CMD INSTALL  \
  '/tmp/RtmpopOLB9/devtoolsb16b7b332274/siddharthab-api-client-r-768cf0a'  \
  --library='/home/pgrosu/apps/R-3.1.0/library' --install-tests

ERROR: dependency âS4Vectorsâ is not available for package âGoogleGenomicsâ
* removing â/home/pgrosu/apps/R-3.1.0/library/GoogleGenomicsâ
Error: Command failed (1)
In addition: Warning message:
package âS4Vectorsâ is not available (for R version 3.1.0)
>
>
> biocLite('S4Vectors')
BioC_mirror: http://bioconductor.org
Using Bioconductor version 2.14 (BiocInstaller 1.14.3), R version
  3.1.0.
Installing package(s) 'S4Vectors'
Warning message:
package âS4Vectorsâ is not available (for R version 3.1.0)
>
```

**Comment by pgrosu** [comment]
Yes, BioC is lower than 3.0 and probably the scripts should be more stringent.  I was basically following the Readme pretending to be a naive user.

**Comment by siddharthab** [comment]
I will fix the readme for now to include the additional command but I will
bring this up with the Bioc team.

**Comment by pgrosu** [comment]
Cool, thanks Sid :)  This would be the BioC team @ Google or the core BioC team?

**Comment by siddharthab** [comment]
Core Bioc team.

**Comment by pgrosu** [comment]
Awesome!

**Comment by seandavi** [comment]
I am one of the bioc core developers, though you'll find much deeper expertise in Martin and the crew in Seattle!  Just a couple of points.  

First, after submitting to Bioconductor, you will not have to worry about older versions.  Bioconductor is "released" every six months, unlike CRAN.  The packages in Bioconductor are released en bloc and are only guaranteed to work within a single version of R (and other release Bioc packages).  

Second, the biocLite.R script first checks if you have the BiocInstaller package already.  If you do, it uses it.  You'll note in the output from https://github.com/googlegenomics/api-client-r/pull/31#issuecomment-76468342 this little note:

```r
> source("http://bioconductor.org/biocLite.R")
Bioconductor version 2.14 (BiocInstaller 1.14.3), ?biocLite for help
A newer version of Bioconductor is available for this version of R,
  ?BiocUpgrade for help
```

This is a mismatch of package versions (in particular, the BiocInstaller package) with R versions, typically arising from having old packages left over from a previous version of R.  Follow the suggestion for BiocUpgrade and you will probably be ready to go.

Hope that helps.

**Comment by pgrosu** [comment]
Thanks Sean, it is great to have you on this project.  Yeah I've been using BioConductor for more than 10 years so I'll explore several of these directions.  Maybe we should have a script that performs a check to ensure a clean environment and queries the user before performing a clean and proper install that is compatible with the functionality of the GoogleGenomics R API client.  What do you think?

~p

**Comment by siddharthab** [comment]
For a manual install, a line in the Readme will suffice. For standard installs, the Bioc infra is good.

**Comment by seandavi** [comment]
I would tend to agree with @siddharthab that sticking to the Bioconductor install instructions is the way to go.  The version mismatch thing comes up every-now-and-then, arising from installation via tarballs or leftover packages from previous R versions, but doing too much to "help" the user can be problematic as well.  If one adheres to biocLite(), these problems generally do not come up.  

As for "manual install", that is definitely not the "bioconductor way" and can lead to problems, particularly when the installer is not familiar with R (sysadmins, for example).  If command-line installation is a must (automated scripting, etc.), then wrapping biocLite(.....) in a small Rscript call from bash is safe and effective.

**Comment by ttriche** [comment]
Hi Sean,

I was thinking of writing a pull request to brute-force this and add
something to DESCRIPTION like

Depends: Biobase ( >= 2.26.0 ) , ...

but this seems cheesy.  It would be great if Depends: could (can?)
explicitly handle a BioC version like that of R, as when one specifies
Depends: R ( >= 3.1.0 ), ... in the DESCRIPTION.

Is there a simple way to force a dependence on "at least BioC-X.Y" in a
package?  If not, would Michael Lawrence and/or BDR sign off on this being
"fixed?"  This comes up on a not-entirely-irregular basis on bioc-devel and
elsewhere.  Seeing as to how Michael is now R-core, if it isn't already
fixed...

Just a thought, mostly along the lines of "can I just address this problem
directly, here, now?"  For some reason I don't have a checkout of r-devel
on my machine right now, otherwise I'd look myself.

**Comment by siddharthab** [comment]
The case here is that BioC maintains entirely separate repos for different versions. So even if we put a package version restriction in the DESCRIPTION file, that new version will not be found in the old repo and you will get a similar error as Paul reported. In the current Bioc setup, what you are asking is effectively for the R dependency system to switch to a different repo when it knows that a package or a package version can be found in  a higher "version" of a repo. R currently does not have a notion of repo versions, and I personally don't think it's worth the effort.

Maybe biocLite can also output the biocUpdatePackages advisory close to error messages like what Paul encountered. Maybe it does already. Personally, I think this is not a problem when the package is part of Bioc. And if we are using developer versions, then we should be able to read the error messages and act on them. I agree it's tricky right now because our developer version is the only version. So the repo Readme should lay out proper instructions. In this case, the Readme did not explicitly say that the Bioc repos must be 3.0 or greater. I can also include in a call to biocUpdatePackages in the installation instructions but that might not be desired by the user in some cases.

The Travis CI system we have in place for this repo does install the package from a clean environment and run all the checks for every change we push. Since the developer version only has to be compatible with devel Bioc, we currently only run these checks against devel Bioc. But this can be easily changed as well to run two parallel tests.

**Comment by seandavi** [comment]
Well-said, @siddharthab.  

Just a note that once you are in the Bioc repository, you are relatively "protected" against breakage since a package that does not build will not replace the previously-built one.  The Bioc build reports are a little delayed (one day, typically) relative to TravisCI, but they are more complete in that Mac, Linux, and Windows are all covered.

**Comment by pgrosu** [comment]
Sean and Sid - I understand and agree, but thinking more about what Tim mentioned, why can't there be an installation script that looks something like this:

```
min.BioC.Version <- "3.0"

get.BioC.Version <- function() {

	tryCatch({
			BiocInstaller::biocVersion() # recent BiocInstaller
		}, error=function(...) {         # no / older BiocInstaller
			BioC_version_associated_with_R_version <-
				get(".BioC_version_associated_with_R_version",
					envir=asNamespace("tools"), inherits=FALSE)
			if (is.function(BioC_version_associated_with_R_version))
				BioC_version_associated_with_R_version()
			else                            # numeric_version
				BioC_version_associated_with_R_version
		})

}

biocVers <- get.BioC.Version()

if ( biocVers < min.BioC.Version ) {
  message( "         Google Genomics requires a newer version of R." )
  stop( "  Please upgrade to the latest version of R." )
}

source("http://bioconductor.org/biocLite.R")
biocLite()
if ( BiocInstaller:::IS_UPGRADEABLE ) {
	biocLite("BiocUpgrade")
}
options(repos=biocinstallRepos())
install.packages("devtools")
devtools::install_github("googlegenomics/api-client-r")
library(GoogleGenomics)
```
Paul

**Comment by siddharthab** [comment]
Because this - http://xkcd.com/1319/

Good spirit Paul, but I think in this case just a comment next to the biocLite command in the Readme will be good. I expect the user to read what he is copy-pasting if it's just 5 lines.

**Comment by pgrosu** [comment]
Good point Sid :)  Yeah, I think the large upgrades I used to do in the past got me too comfortable with layers of encapsulation and automated scripts.  Cool discussion in any case.

Have a great weekend everyone!
~p

**Comment by siddharthab** [comment]
@deflaux I added a little more polish, restored the vignettes, and stopped running authenticated code paths in PRs (secure environment variables are not available in PRs, so we can not authenticate).

In the CONTRIBUTING.rst, I mentioned that a contributor should, for non-trivial changes, set up Travis on his fork and provide the Travis build link in the PR which would have run the authenticated code paths. Here is mine:
https://travis-ci.org/siddharthab/api-client-r/builds/52840404

**Comment by deflaux** [comment]
Nice work Sid!!

@seandavi, @ttriche, and @pgrosu thanks for the discussion!

**Pull request merged**
